[package]
name = "bevy_mod_scripting_core"
version = "0.8.0-alpha.1"
authors = ["Maksymilian Mozolewski <makspl17@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Core traits and structures required for other parts of bevy_mod_scripting"
repository = "https://github.com/makspll/bevy_mod_scripting"
homepage = "https://github.com/makspll/bevy_mod_scripting"
keywords = ["bevy", "gamedev", "scripting", "lua"]
categories = ["game-development"]
readme = "readme.md"

[lib]
name = "bevy_mod_scripting_core"
path = "src/lib.rs"

[features]
# if enabled enables documentation updating in optimized builds
doc_always = []

# if enabled enables some common mlua trait implementations 
mlua_impls = ["mlua"]

[dependencies]
mlua = { version = "0.9", optional = true }

bevy = { workspace = true, default-features = false, features = ["bevy_asset"] }
thiserror = "1.0.31"
paste = "1.0.7"
parking_lot = "0.12.1"
lockable = "0.0.8"
smallvec = "1.11"
itertools = "0.13"
[dev-dependencies]
test_utils = { workspace = true }
