on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'crates/bevy_api_gen/**'
      - 'crates/macro_tests/**'
      - '.github/workflows/release-plz.yml'
      - '.github/workflows/bevy_api_gen.yml'
      - '.github/workflows/macro_tests.yml'
      - 'docs/**'


name: Check and Lint - bevy_mod_scripting

concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check - ${{ matrix.run_args.label }}
    runs-on: ${{ matrix.run_args.os }}
    strategy:
      matrix:
       run_args: [ 
        {label: Windows,        os: windows-latest,      cross: x86_64-pc-windows-msvc    }, 
        {label: MacOS,          os: macOS-latest,        cross: x86_64-apple-darwin       },
        {label: Ubuntu,         os: ubuntu-latest,       cross: x86_64-unknown-linux-gnu  }, 
        {label: Ubuntu Aarch64, os: ubuntu-latest,       cross: aarch64-unknown-linux-gnu }
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install alsa and udev
        if: runner.os == 'linux'
        run: |
          sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
          sudo rm -rf /usr/share/dotnet; sudo rm -rf /opt/ghc; sudo rm -rf "/usr/local/share/boost"; sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - uses: actions-rs/cargo@v1
        with:
          command: xtask ci-check
          components: clippy, rustfmt, grcov, mdbook
          target: ${{ matrix.run_args.cross }}
          args: --workspace --features=lua54,rhai,rune --profile=ephemeral-build